# Generated by Django 2.2.19 on 2021-10-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
